### ISSUE TITLE
Question and a Suggestion

### ISSUE THREAD

**Issue by eteitelbaum** [christopherkenny/congress#19]
Thanks for this great package. I stumbled upon it when I was looking to see how the roll call votes functions provided by `ProPublicaR`, e.g. [this](https://github.com/dietrichson/ProPublicaR/blob/master/R/get_recent_votes.R) or [this](https://github.com/dietrichson/ProPublicaR/blob/master/R/get_votes_by_date.R) now that ProPublica is [shuttering its Congress API](https://www.propublica.org/datastore/api/propublica-congress-api). 

Do you happen to know whether/where the roll call votes that are included in the ProPublica Congress API are included in the Congress.gov API? If they are included, could I use your `congress` package to access them? 

By way of a suggestion, I might have missed it somehow but could not locate any info on the `set_api_key()` function in your documentation. I thought it might be helpful to include that in the documentation and vignette so that people would know how to get started with using the package.

**Comment by christopherkenny** [comment]
Hi @eteitelbaum. First, thanks for the suggestion. The documentation was pretty sparse on that point, so I've added a section to the readme.

You can access roll call votes, but it is not as simple. First, ProPublica does a ton of work which standardized dates, allowing for your second link to work easily. The Congress  API organizes its data by the update date for congress.gov, which may or may not be related to the actual action, e.g. roll call vote, date. (It's never before, obviously, but gets updated at inconsistent times after the action occurs.) Searching for anything that occurs on a specific date is very hard, last I looked into this deeply a few months ago.

Now, if you know a bill number that you're interested in or many such bills, you can get the roll call votes like so. `congress` will get you the URLs to get vote data, but does not itself process that data. I've included a short parse function that can process them using `xml2` and `dplyr`.

```
library(congress)
library(dplyr)

# https://www.congress.gov/bill/118th-congress/senate-bill/4361
actions <- cong_bill(congress = 118, type = 's', number = 4361, item = 'actions')
vote_urls <- actions |> 
  filter(!is.na(recorded_votes_url)) |> 
  pull(recorded_votes_url)


parse_roll_call_vote <- function(url) {
  l <- xml2::read_xml(url) |> 
    xml2::as_list()
  
  lapply(l$roll_call_vote$members, \(x) bind_rows(unlist(x))) |> 
    bind_rows()
}

rcv <- lapply(vote_urls, parse_roll_call_vote)

rcv[[1]]
```

**Comment by eteitelbaum** [comment]
@christopherkenny Thank you so much for this super-helpful response!
