### ISSUE TITLE
No observations returned after inputting a date range

### ISSUE THREAD

**Issue by uctsk** [christopherkenny/congress#8]
Hello,

Many thanks for developing this package! I'm having an issue where the function cong_bill() is not returning any observations or columns when I set a from_date and to_date. The function works just fine when I remove the date parameters. Would you have any insight into why this might be happening? I've tried a few different date ranges but none seem to work. I'm including the code below in case that's helpful.

`df_cong <- cong_bill(congress = 116,
                     type = 'hr',
                     limit = 250,
                     from_date = '2020-12-18',
                     to_date = '2020-12-31')`

Many thanks again!

**Comment by christopherkenny** [comment]
Hmm, that is very weird. Something with the dates seems to work, as we can run:

```
library(congress)
df_cong <- cong_bill(congress = 116, type = 'hr', limit = 250, from_date = '2020-12-18', to_date = '2022-12-31')
```
That gives us 250 bills. It seems to give different bills if we use the offset parameter too. 

Inspecting the internal call with `httr2::last_request()` also seems to give the right format. So on first glance, I'm not sure what's going wrong. I will poke around.

**Comment by uctsk** [comment]
That's odd for sure! I'll play around more with the dates but let me know if there's a better work around.

Thanks so much for looking into this!

**Comment by uctsk** [comment]
Hmm, I didn't realize it was by bill updated date. One of the bills that I was expecting to see in that time period was the College Affordability Act (reported to the house 12/28/2020 per the congress website: https://www.congress.gov/bill/116th-congress/house-bill/4674?q=%7B%22search%22%3A%5B%22College+Affordability+Act%22%5D%7D&s=7&r=4

I wonder whether the date on the website is different that that the "updated" date?

**Comment by uctsk** [comment]
Ah, that makes sense. Many thanks for looking into this! I very much appreciate the help!

**Comment by christopherkenny** [comment]
As far as I know, there is no way to search by those using the beta version of the API.
